// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241216204829_initial_tables")]
    partial class initial_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Authentication.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Authentication.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Miguel de Cervantes",
                            AvailableCopies = 5,
                            Genre = "Roman",
                            ISBN = "9780060934347",
                            Language = "İspanyolca",
                            PageCount = 992,
                            PublicationYear = 1605,
                            Publisher = "Harper & Row",
                            Summary = "Don Quixote is the story of a man who, after reading too many chivalric romances, decides to become a knight-errant and have adventures with his squire, Sancho Panza.",
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Herman Melville",
                            AvailableCopies = 4,
                            Genre = "Roman",
                            ISBN = "9781503280786",
                            Language = "İngilizce",
                            PageCount = 635,
                            PublicationYear = 1851,
                            Publisher = "Richard Bentley",
                            Summary = "Moby-Dick tells the adventures of the wandering sailor Ishmael, and his voyage on the whaleship Pequod, commanded by Captain Ahab, who is determined to hunt down the giant white whale Moby Dick.",
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            AvailableCopies = 10,
                            Genre = "Roman",
                            ISBN = "9781503290563",
                            Language = "İngilizce",
                            PageCount = 279,
                            PublicationYear = 1813,
                            Publisher = "T. Egerton, Whitehall",
                            Summary = "The novel follows the life of Elizabeth Bennet as she deals with issues of manners, marriage, and family in early 19th-century England.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Leo Tolstoy",
                            AvailableCopies = 3,
                            Genre = "Tarihi Roman",
                            ISBN = "9780140447934",
                            Language = "Rusça",
                            PageCount = 1225,
                            PublicationYear = 1869,
                            Publisher = "The Russian Messenger",
                            Summary = "War and Peace chronicles the history of the Napoleonic wars in Russia and the intertwined lives of several aristocratic families.",
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 5,
                            Author = "George Orwell",
                            AvailableCopies = 6,
                            Genre = "Distopya",
                            ISBN = "9780451524935",
                            Language = "İngilizce",
                            PageCount = 328,
                            PublicationYear = 1949,
                            Publisher = "Secker and Warburg",
                            Summary = "1984 is a dystopian novel set in a totalitarian society controlled by a figure known as Big Brother. The protagonist, Winston Smith, tries to rebel against the oppressive regime.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 6,
                            Author = "F. Scott Fitzgerald",
                            AvailableCopies = 7,
                            Genre = "Roman",
                            ISBN = "9780743273565",
                            Language = "İngilizce",
                            PageCount = 180,
                            PublicationYear = 1925,
                            Publisher = "Charles Scribner's Sons",
                            Summary = "The Great Gatsby tells the story of Jay Gatsby's quest to win back his lost love, Daisy Buchanan, amidst the excess and decadence of the Roaring Twenties.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Fyodor Dostoevsky",
                            AvailableCopies = 8,
                            Genre = "Psikolojik Roman",
                            ISBN = "9780486454115",
                            Language = "Rusça",
                            PageCount = 430,
                            PublicationYear = 1866,
                            Publisher = "The Russian Messenger",
                            Summary = "Crime and Punishment tells the story of Rodion Raskolnikov, a young man who plans and carries out the murder of an old pawnbroker and then struggles with guilt and moral dilemmas.",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Homer",
                            AvailableCopies = 2,
                            Genre = "Destan",
                            ISBN = "9780140268867",
                            Language = "Eski Yunanca",
                            PageCount = 541,
                            PublicationYear = -800,
                            Publisher = "Penguin Classics",
                            Summary = "The Odyssey is an epic poem that tells the story of Odysseus's journey home after the fall of Troy, including encounters with mythical creatures and divine forces.",
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Harper Lee",
                            AvailableCopies = 9,
                            Genre = "Roman",
                            ISBN = "9780061120084",
                            Language = "İngilizce",
                            PageCount = 281,
                            PublicationYear = 1960,
                            Publisher = "J.B. Lippincott & Co.",
                            Summary = "To Kill a Mockingbird tells the story of a young girl named Scout Finch growing up in the racially segregated South, and her father, Atticus Finch, defending a black man accused of raping a white woman.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.D. Salinger",
                            AvailableCopies = 4,
                            Genre = "Roman",
                            ISBN = "9780316769488",
                            Language = "İngilizce",
                            PageCount = 277,
                            PublicationYear = 1951,
                            Publisher = "Little, Brown and Company",
                            Summary = "The Catcher in the Rye follows Holden Caulfield, a disaffected teenager who is struggling with alienation and depression after being expelled from prep school.",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Antoine De Saint Exupery",
                            AvailableCopies = 1500,
                            Genre = "Roman",
                            ISBN = "9786257751353",
                            Language = "Türkçe",
                            PageCount = 96,
                            PublicationYear = 2021,
                            Publisher = "Kapra Yayıncılık",
                            Summary = "Antoine De Saint-Exupéry’nin Küçük Prens’i, çağdaş dünya edebiyatının en çok okunan ve belki de en çok sevilen eseri. Sadece çocukların değil, çocukluğunu içinde korumayı başarmış yetişkinlerin de büyük keyif alarak okuduğu bu eser, yazıldığı günden bu yana hemen hemen bütün dünya dillerine çevrilerek adeta insanlığın ortak miraslarından birine dönüşmüş durumda.“Ne esrarengiz bir olay. Evrende bir yerlerde, daha önce hiç görmediğimiz bir koyunun gülü yiyip yemediği, Küçük Prens’i çok seven bizler için ne kadar da önemli. Gökyüzüne bakın ve kendi kendinize şu soruyu sorun: ‘Koyun çiçeği yedi mi yemedi mi?’ Her şey nasıl da değişiyor göreceksiniz. Hiçbir yetişkin, bunun ne denli önemli olduğunu anlayamayacaktır!”",
                            Title = "Küçük Prens"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
